### ISSUE TITLE
Markdown-it-admonition body padding

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#17]
In tutorial, _("This is the admonition body")_ part has **padding** from the header .  
However it is not the case on final deployment.

### Expected behavior
![image](https://user-images.githubusercontent.com/385958/41290382-baabac84-6e1a-11e8-8ebe-3aa98763c9b6.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/385958/41290476-fe8a1c9c-6e1a-11e8-96e2-c095b77ee7f6.png)

**Comment by qjebbs** [comment]
This is a known issue, caused by [Markdown Preview Github Styling](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles), you got good padding if you stop that extension. We should start an issue to that repo.

**Comment by cilerler** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/84fe956e-bbff-4d6e-8517-fa8a6614910e-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)

**Comment by cilerler** [comment]
It looks like it is not **Markdown Preview Github Styling**

![image](https://user-images.githubusercontent.com/385958/41326075-50a03d34-6e8b-11e8-9677-d050d08ac39b.png)

**Comment by qjebbs** [comment]
Try disable all styling extensions, and user styles in user setting. I tested it good, when I use vscode default theme

**Comment by cilerler** [comment]
You were right, there was a user style in user setting _(we added that one to support **markdown-it-container**)_

![bitmoji](https://render.bitstrips.com/v2/cpanel/84fe956e-bbff-4d6e-8517-fa8a6614910e-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)

**Comment by qjebbs** [comment]
Relevant code in  Markdown Preview Github Styling is:

```css
.vscode-body p,
.vscode-body blockquote,
.vscode-body ul,
.vscode-body ol,
.vscode-body dl,
.vscode-body table,
.vscode-body pre {
  margin-top: 0px; /*should be 16px*/
  margin-bottom: 16px;
}
```
