### ISSUE TITLE
Problem: Markdown file with pupperteer configuration

### ISSUE THREAD

**Issue by c4tom** [qjebbs/vscode-markdown-extended#88]
Hi, thank you, first I want to thank you for this project

I'm having trouble using this in the markdown file

please, can you help me?

```
---
puppeteer:
    pdf:
        format: A4
		  displayHeaderFooter: true
		  headerTemplate: "<span class='pageNumber'></span>"
        margin:
            top: .7cm
            right: .7cm
            bottom: .9cm
            left: .7cm
    image:
        quality: 100
        fullPage: true
---



ERROR:
can not read a block mapping entry; a multiline key may not be an implicit key at line 6, column 15:
            margin:
                  ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 6, column 15:
            margin:
                  ^
	at generateError (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
	at throwError (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
	at readBlockMapping (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
	at composeNode (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
	at readDocument (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
	at loadDocuments (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
	at Object.load (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
	at new MetaData (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/out/src/services/common/meta.js:7:27)
	at MarkdownDocument.load (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/out/src/services/common/markdownDocument.js:38:22)
	at new MarkdownDocument (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/out/src/services/common/markdownDocument.js:8:14)
	at PuppeteerExporter.<anonymous> (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/out/src/services/exporter/puppeteer.js:59:28)
	at Generator.next (<anonymous>)
	at fulfilled (/home/can/.vscode/extensions/jebbs.markdown-extended-1.0.17/out/src/services/exporter/puppeteer.js:4:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by qjebbs** [comment]
You had a bad formatted yaml header, try this:

```
puppeteer:
    pdf:
        format: A4
        displayHeaderFooter: true
        headerTemplate: "<span class='pageNumber'></span>"
        margin:
            top: .7cm
            right: .7cm
            bottom: .9cm
            left: .7cm
    image:
        quality: 100
        fullPage: true
```
